name: 'GitHub Release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release (e.g. 1.2.3)'
        required: false
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        uses: open-resource-discovery/github-release@1394005a81f4065a076e4071983bb9802a9e5e10 # main
        with:
          tag-template: 'v<version>'
          version: ${{ inputs.version }}
