name: Release

on:
  workflow_dispatch:
    inputs:
      docker:
        description: 'Docker Image'
        required: false
        type: boolean
        default: true

jobs:
  docker:
    if: inputs.docker
    runs-on: ubuntu-latest
    environment: docker-registry
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Set Docker Tags
        id: docker_tags
        run: |
          VERSION=$(node -p -e "require('./package.json').version")
          TAGS=""

          if [[ $VERSION =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
            TAGS="ghcr.io/${{ github.repository }}:latest"
          fi

          TAGS="$TAGS,ghcr.io/${{ github.repository }}:$VERSION"
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "$TAGS"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_tags.outputs.tags }}
